site_name: Portal Oficial de Documentación
site_description: Manuales técnicos, guías de instalación y arquitectura del sistema.
site_author: Estudiantes de 3ro Software - Complejo Educativo Delgado

theme:
  name: material
  language: es

nav:
  - Inicio: index.md
  - Manuales Técnicos:
      - Arquitectura y Despliegue: arquitectura_despliegue.md
      - Guía de Instalación: instalacion_movil.md
      - Especificación de API: api_endpoints.md
      - Seguridad y Mantenimiento: seguridad.md
